project:
  type: website

website:
  title: "Greg Maya"
  description: "Location-Based Problem Solving"
  search: false  
  open-graph:
    locale: en_UK
  navbar:
    background: primary
    left:
      - text: "About"
        href: about.qmd
      - text: "Works"
        href: work/index_work.qmd
      - text: "Services"
        href: services/index_services.qmd
      - text: "CV"
        href: "CV - Greg Maya.pdf"

  sidebar:
      #title: Works
      style: "docked"
      border: false
      collapse-level: 1
      contents:
      - section: "Data Visualisation"
        contents:
        - text: NFI - City Pulse
          href : work/data_viz/nfi_city_pulse.qmd
        - text: J-Graphs
          href : work/data_viz/jgraph.ipynb
        - text: Article 19
          href : work/data_viz/article19.qmd
        - text: End Child Poverty
          href : work/data_viz/end_ch_poverty.qmd
      
      - section: "Urban Planning"
      #  contents:
      #  - text: Jilin squares
      #  - text: Roundabout Simplification
      #    href: work/urban/rab_simpl.qmd
      #  - text: Paddington navigation & Placemanking
      #  - text: Bogota early diagnosis

      - section: "Architecture & Strategy"
      #  contents:
      #  - text: ASOS Studios
      #  - text: Legal & General (L&G)
      #  - text: Southback Center - workplace
      #  - text: Building Research Unit
      #    href: work/archi/bru.qmd
      #  - text: Sense of Place @ TATE Modern
        

      - section: "Others"
        contents: 
        - text: Talks
          href: work/others/talks.qmd
        - text: Articles
          href: work/others/articles.qmd
      
  page-footer:
    center: "© Copyright 2024 Greg Maya. Except where otherwise noted. All text and images licensed CC-BY-NC 4.0."

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css 
execute:
  engine: jupyter-python
  kernel: python3
  path: geo_env/bin/python  # Adjust this path according to your setup
  freeze: auto