---
title: "Location-Based Problem Solving"
about:
  template: trestles
---

I am Gregorio Maya, a senior spatial data consultant currently based in Madrid, (Spain).

I am passionate about discovering the cues that drive behaviour in the built environment. With an MSc in Space Syntax and an honours Degree in Architecture, over the last 9 years in industry (urban consultancy, workplace strategy, and tech development) I have leveraged technical skills of data science to inform desing and policy based on data analysis and visualization.

More recently, I have been collaborating with open source projects with PySAL devs (Python Spatial Analysis Libraries).

Academic activities are also a complementary part of my professional development. I am a frequent (virtual) lecturer at Universidad de los Andes (COL) and I often collaborate with professors at UCA Carnterbury (UK) and Universidad Nacional del Litoral (ARG).

:::: {.columns}

::: {.column width="45%"}
## Mission
To work across disciplines to surface the hidden properties of the built environment.

:::

::: {.column width="10%"}
<!-- empty column to create gap -->
:::

::: {.column width="45%"}
## Vision
A built-environemnt industry that embraces the opportunities that lie in space to trigger positive social behaviours.

:::

::::

## Languages

- Spanish (native)
- English (100% fluent)
- French (100% fluent)
- Portuguese (conversational)